
@token = aaaaaaaaaaaaaaaaaaaaaaaaa
@host_port = http://localhost:3000


### get user 1
GET {{host_port}}/api/web/user/getUserById/1 HTTP/1.1

### get user 2
GET {{host_port}}/api/web/user/getUserById/1 HTTP/1.1


### api root
GET {{host_port}}/ HTTP/1.1



### post test demo
POST {{host_port}}/api/v1/public/echo HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: iPhone

test=1
&bundle_id=demo
&msg=123123
&token={{token}}
